framework:
    messenger:
        default_bus: command.sync.bus
        buses:
            command.sync.bus:
#            command.async.bus:
        serializer:
            default_serializer: messenger.transport.symfony_serializer
            symfony_serializer:
                format: json
                context: { }
        transports:
            sync: 'sync://'
#            async:
#                dsn: '%env(MESSENGER_DOCTRINE_TRANSPORT_DSN)%'
#                options:
#                    queue_name: async
#                    auto_setup: false
#                retry_strategy:
#                    max_retries: 3
#                    delay: 1000
#                    multiplier: 2
#            failed:
#                dsn: '%env(MESSENGER_DOCTRINE_TRANSPORT_DSN)%'
#                options:
#                    queue_name: failed
#                    auto_setup: false

        routing:
            App\Shared\Application\Command\Sync\Command: sync
#            App\Shared\Application\Command\Async\Command: async

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
