parameters:
    baselinker.api_token: '%env(BASELINKER_API_TOKEN)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    _instanceof:
        App\Order\Infrastructure\Marketplace\MarketplaceInterface:
            tags: [ baselinker.marketplace_provider ]

        App\Shared\Application\Command\Sync\CommandHandler:
            tags:
                - { name: 'messenger.message_handler', bus: command.sync.bus }

    App\Order\Infrastructure\BaseLinker\Client\BaseLinkerClient: ~

    App\Order\Infrastructure\BaseLinker\Client\BaseLinkerClientInterface:
        alias: App\Order\Infrastructure\BaseLinker\Client\Decorator\StopwatchBaseLinkerClient

    App\Order\Infrastructure\BaseLinker\Client\Decorator\LoggingBaseLinkerClient:
        arguments:
            $inner: '@App\Order\Infrastructure\BaseLinker\Client\BaseLinkerClient'

    App\Order\Infrastructure\BaseLinker\Client\Decorator\StopwatchBaseLinkerClient:
        arguments:
            $inner: '@App\Order\Infrastructure\BaseLinker\Client\Decorator\LoggingBaseLinkerClient'

    App\Order\Infrastructure\Marketplace\MarketplaceProvider:
        arguments:
            $strategies: !tagged_iterator baselinker.marketplace_provider
