services:
    _defaults:
        public: true

    # Make test dependencies public so they can be replaced in tests
    App\Order\Infrastructure\BaseLinker\Client\BaseLinkerClientInterface:
        alias: 'App\Order\Infrastructure\BaseLinker\Client\Decorator\StopwatchBaseLinkerClient'
        public: true
    App\Order\Infrastructure\Repository\OrderRepositoryInterface:
        alias: 'App\Order\Infrastructure\Repository\InMemoryOrderRepository'
        public: true
